### ISSUE TITLE
datetime_diff has strange result

### ISSUE THREAD

**Issue by TANGLIHUI** [MicrosoftDocs/dataexplorer-docs#1203]
[Enter feedback here]
I got this, anyone explain it please!
![image](https://user-images.githubusercontent.com/25787018/170664349-84592161-db86-4e53-85eb-d98aef469f49.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7d3f626-bc42-8e9b-12da-c6349e698076
* Version Independent ID: 79e92c50-4110-5782-dcda-6d0ff93dbc23
* Content: [datetime_diff() - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/datetime-difffunction)
* Content Source: [data-explorer/kusto/query/datetime-difffunction.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/main/data-explorer/kusto/query/datetime-difffunction.md)
* Service: **data-explorer**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by KranthiPakala-MSFT** [comment]
@TANGLIHUI Thanks for leveraging Azure docs feedback channel to raise this question. This channel is reserved for ‘Azure docs’ feedback- for sharing doc feedback and suggesting content improvements. We didn't determine any changes for this documentation upon reviewing this feedback.

If your issue is specific to a use case, we request you to please reach out in forums like [Microsoft Q&A](https://docs.microsoft.com/answers/index.html) or [Stackoverflow](https://stackoverflow.com/questions). We have our engineers and other community members who will be happy to assist. Forums have a better suited audience for such queries. Once your issue is posted in forum, please do share the forum thread link here for tracking. 

If you have a document which you are following and if you think it needs an update, please let us know about that here.

We will now proceed to close this thread. If there are further questions regarding this matter, please reopen it and we will gladly continue the discussion.

Thank you
