### ISSUE TITLE
Kusto UDF - time_weighted_avg_fl() is giving all zero's as result

### ISSUE THREAD

**Issue by srjhunjhunwalacorp** [MicrosoftDocs/dataexplorer-docs#1304]
I am using "time_weighted_avg_fl()" UDF but all the results returned as value zero event after adjusting the aggregation window.

**Comment by ShaikMaheer-MSFT** [comment]
@srjhunjhunwalacorp Thanks for the feedback. We are actively validating it. We will check and back to you

**Comment by KranthiPakala-MSFT** [comment]
Thanks for leveraging Azure docs feedback channel to raise this question. This channel is reserved for ‘Azure docs’ feedback- for sharing doc feedback and suggesting content improvements. We didn't determine any changes for this documentation upon reviewing this feedback.

If your issue is specific to a use case, we request you to please reach out in forums like [Microsoft Q&A](https://docs.microsoft.com/answers/index.html) or [Stackoverflow](https://stackoverflow.com/questions). We have our engineers and other community members who will be happy to assist. Forums have a better suited audience for such queries. Once your issue is posted in forum, please do share the forum thread link here for tracking. 

If you have a document which you are following and if you think it needs an update, please let us know about that here.

Thank you

**Comment by srjhunjhunwalacorp** [comment]
> Thanks for leveraging Azure docs feedback channel to raise this question. This channel is reserved for ‘Azure docs’ feedback- for sharing doc feedback and suggesting content improvements. We didn't determine any changes for this documentation upon reviewing this feedback.
> 
> If your issue is specific to a use case, we request you to please reach out in forums like [Microsoft Q&A](https://docs.microsoft.com/answers/index.html) or [Stackoverflow](https://stackoverflow.com/questions). We have our engineers and other community members who will be happy to assist. Forums have a better suited audience for such queries. Once your issue is posted in forum, please do share the forum thread link here for tracking.
> 
> If you have a document which you are following and if you think it needs an update, please let us know about that here.
> 
> Thank you

Hi,

I am referring to the UDF provided in the document "https://github.com/MicrosoftDocs/dataexplorer-docs/tree/main/data-explorer/kusto/functions-library"  for time weighted average, which is not resulting correct output.

**Comment by adieldar** [comment]
In order to check this issue we need full details including the specific input and the KQL query. Best would be if you can generate using the datatable operator a minimal input that manifests the issue

**Comment by YaelSchuster** [comment]
Hi @srjhunjhunwalacorp - since there has been no response in over a week, I'm closing this issue. Please feel free to @mention one of us to reopen with more information. 

#please-close
