### ISSUE TITLE
Update Policy on queries that joined tables thus relying on different  table sources

### ISSUE THREAD

**Issue by oblancke** [MicrosoftDocs/dataexplorer-docs#1313]
Dear Microsoft Team,

I would be interested in knowing possibilities to apply update policy on queries that applied tables join. Is there any limitation if query relies on differents table sources? 

Thanks
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 26bac25c-c168-fadc-2491-651d35361512
* Version Independent ID: 608aa328-7799-1597-0940-4edec0b93e08
* Content: [Kusto update policy - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/management/updatepolicy)
* Content Source: [data-explorer/kusto/management/updatepolicy.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/main/data-explorer/kusto/management/updatepolicy.md)
* Service: **data-explorer**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by KranthiPakala-MSFT** [comment]
Thanks for leveraging Azure docs feedback channel to raise this question. This channel is reserved for ‘Azure docs’ feedback- for sharing doc feedback and suggesting content improvements. We didn't determine any changes for this documentation upon reviewing this feedback.

If your issue is specific to a use case, we request you to please reach out in forums like [Microsoft Q&A](https://docs.microsoft.com/answers/index.html) or [Stackoverflow](https://stackoverflow.com/questions). We have our engineers and other community members who will be happy to assist. Forums have a better suited audience for such queries. Once your issue is posted in forum, please do share the forum thread link here for tracking. 

If you have a document which you are following and if you think it needs an update, please let us know about that here.

Thank you

**Comment by KranthiPakala-MSFT** [comment]
We will now proceed to close this thread. Once your issue is posted in forum, please do share the forum thread link here for tracking.

Thank you
