### ISSUE TITLE
Getting the following error when trying to execute kusto queries using powershell. "New-Object : Exception calling ".ctor" with "2" argument(s): "The type initializer for 'Kusto.Data.KustoConnectionStringBuilder' threw an exception."

### ISSUE THREAD

**Issue by chidhambaram55** [MicrosoftDocs/dataexplorer-docs#1361]
[Enter feedback here]

Hi Team,
Iam currently trying to execute kusto queries using powershell. I was able to successfully execute kusto queries using net472 version on powershell version 5.1. But i am trying to execute kusto queries using powershell version 6.2.2. According to the following Doc: https://docs.microsoft.com/en-us/powershell/scripting/whats-new/differences-from-windows-powershell?view=powershell-7.2
![image](https://user-images.githubusercontent.com/74607402/185669771-b35dad38-a6f1-474b-901b-21cba48b4d91.png)
powershell 6.2 is built on netcore2.1. Therefore i used netcore2.1 kusto tool but it is throwing the following error:
![image](https://user-images.githubusercontent.com/74607402/185669805-90ffe661-ca1d-4111-9f7e-9b51f14257b4.png)

PowershellVersion iam using:
![image](https://user-images.githubusercontent.com/74607402/185669835-2bbd0e5c-be16-4ed8-b414-bc64b1d3c624.png)

Result after loading the package:
![image](https://user-images.githubusercontent.com/74607402/185669863-77ccd8fe-30a9-4ded-b00b-4e2dc905d725.png)

Please help me in figuring out the issue. Thanks.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c2df80c7-1cca-9c8d-0ed5-05b387e1850f
* Version Independent ID: d3f5e3ed-dc62-ca1a-c821-4ca25453fa0f
* Content: [Kusto .NET Client Libraries from PowerShell - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/api/powershell/powershell)
* Content Source: [data-explorer/kusto/api/powershell/powershell.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/main/data-explorer/kusto/api/powershell/powershell.md)
* Service: **data-explorer**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by KranthiPakala-MSFT** [comment]
Thanks for leveraging Azure docs feedback channel to raise this question. This channel is reserved for ‘Azure docs’ feedback- for sharing doc feedback and suggesting content improvements. We didn't determine any changes for this documentation upon reviewing this feedback.

If your issue is specific to a use case, we request you to please reach out in forums like [Microsoft Q&A](https://docs.microsoft.com/answers/index.html) or [Stackoverflow](https://stackoverflow.com/questions). We have our engineers and other community members who will be happy to assist. Forums have a better suited audience for such queries. Once your issue is posted in forum, please do share the forum thread link here for tracking. 

If you have a document which you are following and if you think it needs an update, please let us know about that here.

Thank you

**Comment by CHEEKATLAPRADEEP-MSFT** [comment]
@chidhambaram55  We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
