### ISSUE TITLE
How can I use the time range paramter for `make-area` operator in the dashboard?

### ISSUE THREAD

**Issue by justinmchase** [MicrosoftDocs/dataexplorer-docs#1468]
The `| make-series ...` function appears to require a timespan explicitly in the query but in the dashboard there is a timespan parameter by default. I'm not sure how to utilize that. Omitting `from ago(24hrs) to now()` causes it to fail to parse or return an error saying there is a column missing.

#### This query works for me, but the from/to is hard coded
```
| make-series Count = count() on TimeGenerated from ago(24hrs) to now() step 1hr by Topic
| render areachart
```

#### This query fails with the following error

```
| make-series Count = count() on TimeGenerated step 1hr  by Topic
```
> Failed to create visualization
> The Stacked Area can't be created as you are missing a column of one of the following types: int, long, decimal or real

#### So how can I have my query utilize this variable ↴

![image](https://user-images.githubusercontent.com/10974/197814942-07e4264c-609d-44fe-8490-ca8ec4e75c5b.png)

If its possible or not possible, it would be helpful to have an area in this documentation explaining how this syntax can interact with the default time range.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4e79e226-f1e1-b6ec-f4aa-1a66818190b4
* Version Independent ID: 49dba61b-3968-ac88-e2b2-49fd27942f61
* Content: [make-series operator - Azure Data Explorer](https://learn.microsoft.com/en-us/azure/data-explorer/kusto/query/make-seriesoperator)
* Content Source: [data-explorer/kusto/query/make-seriesoperator.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/main/data-explorer/kusto/query/make-seriesoperator.md)
* Service: **data-explorer**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by AjayBathini-MSFT** [comment]
@justinmchase 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by RamanathanChinnappan-MSFT** [comment]
@justinmchase 

Since this issue isn't directly related to improving our docs, and to gain a better understanding of your issue, I'd recommend working closer with our support team via an [Azure support request] (https://docs.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request). Or you can leverage our Q&A forum by posting your issue there so our community, and MVPs can further assist you in troubleshooting this issue or finding potential workarounds.



[Teams Q&A forum] (https://docs.microsoft.com/en-us/answers/topics/46488/office-teams-windows-itpro.html) for technical questions about the configuration and administration of Microsoft Teams on Windows.
[Microsoft Teams Community forum] (https://answers.microsoft.com/en-us/msteams/forum?sort=LastReplyDate&dir=Desc&tab=All&status=all&mod=&modAge=&advFil=&postedAfter=&postedBefore=&threadType=All&isFilterExpanded=false&page=1

**Comment by justinmchase** [comment]
@RamanathanChinnappan-MSFT

> ... it would be helpful to have an area in this documentation explaining how this syntax can interact with the default time 
range.

I went to your docs and it didn't give a sufficient explanation. Even having a section in the documentation that said its not supported would have helped your support team to not field an addition ticket just to ask a question about something that should be in the docs.
