### ISSUE TITLE
Dashboard Time Parameters - What is the Time Zone? Is it translated automatically to UTC?

### ISSUE THREAD

**Issue by clarkbreyman-yammer** [MicrosoftDocs/dataexplorer-docs#1477]
My timestamp data is in UTC. I can't tell if the dashboard time parameters are adjusting to UTC from my browser locale of PDT. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7fdcd90e-7d08-39e9-c2e5-888c690c6cbc
* Version Independent ID: 525bd933-5da2-29b5-8d7c-dadfa094c9f0
* Content: [Parameters in Azure Data Explorer dashboards](https://learn.microsoft.com/en-us/azure/data-explorer/dashboard-parameters)
* Content Source: [data-explorer/dashboard-parameters.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/main/data-explorer/dashboard-parameters.md)
* Service: **data-explorer**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by RamanathanChinnappan-MSFT** [comment]
@clarkbreyman-yammer 

Thanks for your feedback! We will investigate and update as appropriate.

**Comment by YaelSchuster** [comment]
Thanks for contacting us with feedback about our product documentation. Depending on the complexity, it could take from a few business days to a few weeks to look further into your question, issue, or suggestion. We'll contact you if we need further information, and you'll receive an email message each time we "@mention" you in a comment.

Thanks again for submitting your feedback. Your suggestions help improve our documentation.

**Comment by Weffe** [comment]
Hi @clarkbreyman-yammer, the way Dashboards works with time zones is that whatever time zone you have set in your User Settings, it will automatically display your timestamp data and parameters in that zone. It will always treat the user setting's time zone as the source of truth and will disregard your local zone (PDT).

The reason it's like this is because we wanted to let customers easily see timestamps in certain time zones by just changing their user settings instead of needing to adjust their computer or browser wide settings.

However, when sending the parameter datetime value to kusto it will send the raw datetime string you have set and it will not do any conversions.

Here's a quick guide over this:
## For datetime/duration parameters

1. Let's ensure we are in UTC time zone to start

![image](https://user-images.githubusercontent.com/6274727/200653589-197c1d88-e5f2-445d-9e19-300a67327471.png)

2. Then, create a datetime parameter with some sample dates

![image](https://user-images.githubusercontent.com/6274727/200653422-0509dd12-193c-4e68-bde7-4b812c5c4b65.png)

3. We can create a tile to display the value 

![image](https://user-images.githubusercontent.com/6274727/200653743-4a4a7796-2acd-4366-983f-449f41c34b95.png)

4. Now if we change the time zone in user settings to US/Pacific you can see the value get zoned

![image](https://user-images.githubusercontent.com/6274727/200653917-119d0273-c686-4182-84d6-106a2eda27a9.png)

5. Same thing happens if we choose a zone ahead of UTC

![image](https://user-images.githubusercontent.com/6274727/200654865-9630dfc7-83b0-4488-9d3b-190fcb3f2ac8.png)


## For datetime columns

1. Let's create a datatable with some sample datetimes while my user settings are set to UTC

KQL:

```
datatable (name: string, timestamp: datetime) [ 
    'Alpha', datetime(2014-10-01 0:0:0.0),
    'Bravo', datetime(2015-12-31 0:0:0.0),
]
```

Screenshot:

![image](https://user-images.githubusercontent.com/6274727/200645160-1568e13a-40cc-4642-9c80-e11c714eb463.png)

7. If I change the time zone settings to PDT (a.k.a US/Pacific), you will see the timestamps get automatically adjusted back.

Screenshot:

![image](https://user-images.githubusercontent.com/6274727/200645637-2d1b85d0-01fe-4d16-bb42-0c367c17d8bb.png)

8. And the same will happen if I choose a zone that's ahead of UTC, the timestamps will get adjusted forward.

![image](https://user-images.githubusercontent.com/6274727/200646294-abe14075-54cc-4543-b96f-44d16334ca45.png)

**Comment by YaelSchuster** [comment]
Thanks @weffe for the thorough explanation.

@clarkbreyman-yammer I'm going to close the issue at this time. If you have further questions, please feel free to reopen or @mention us for clarifications.

#please-close
