### ISSUE TITLE
Complex join key

### ISSUE THREAD

**Issue by mathaholic** [MicrosoftDocs/dataexplorer-docs#1497]
please add an example of 

let b = table
           |some logic
           |distinct keyB, keyD, col1, col2;
a
| join kind=inner (b) on $left.keyA == $right.keyB, $left.keyC == $right.keyD

I've tried all permutations listed here:
https://stackoverflow.com/questions/58867033/kusto-kql-join-on-multiple-columns
and none of them worked

**Comment by SaibabaBalapur-MSFT** [comment]
@mathaholic 
Thanks for your feedback! We will investigate and update as appropriate.

Since this channel is for driving improvements towards MS Docs, could you provide the URL of the specific documentation that your feedback is applicable to? That way, we are able to make sure your feedback is addressed by the right team

**Comment by mathaholic** [comment]
@SaibabaBalapur-MSFT https://learn.microsoft.com/en-us/azure/data-explorer/kusto/query/joinoperator?pivots=azuredataexplorer
