### ISSUE TITLE
[PROPOSAL] Add description on what hash function under "Link to clipboard" button

### ISSUE THREAD

**Issue by arsamigullin** [MicrosoftDocs/dataexplorer-docs#1585]
Hi everyone, 

I need to compose a link to Azure Data Explorer (ADX) that would also contain a query. Once user clicks on the link, the ADX opens up in the browser and the query from URL is executed. 

Was able to pass a small query (less than 2048 chars) to the URL with %20 and %0D%0A symbols and it works well. However, now I need to pass a much larger query. Noticed that ADX Web UI contains "Link to clipboard" button that creates a URL with a hashed query in it. In my case I would like to use the same approach but I do not know what hash function is used there. From that couple of questions

1. Can you please say what hash function is used to compose the query?
2. Can you please add this information to the documentation?

**Comment by RamanathanChinnappan-MSFT** [comment]
@jpsebasti 

It would be great if you could add a link to the documentation you are following for these steps? This would help us redirect the issue to the appropriate team. Thanks!!

**Comment by arsamigullin** [comment]
Hi, there is no specific documentation on how to compose URL with the query in it

This is an example of URL generated by "Link to clipboard" button, here we see that the query parameter is assigned the hash of the query. I would like to understand what function is used to compose this hash.

https://dataexplorer.azure.com/clusters/<cluster>.eastus/databases/<database>?**query**=H4sIAAAAAAAAA8tJLVEIUbBVSEksAcKknFSN5Pyc0tw8Q6vMvBIdBQjHyKq4pCgzL12Tlyual0tBwVBHQclRSQfENAIynSBMYyDTWYmXK9aalyuEl6umPCO1KBVqgqGCra2CIQCl9dQabQAAAA==

Instead of passing hash, I passed text query with %20 and %0D%0A symbols and it worked. The URL look like this

https://dataexplorer.azure.com/clusters/<cluster>.eastus/databases/<database>?**query**=let%20T%20=%20datatable(column1:int,%20column2:string)%0D%0A[%0D%0A%20%201,%20"A",%0D%0A%20%202,%20"B",%0D%0A%20%203,%20"C"%0D%0A];T|where%20column1%20==%201

**Comment by arsamigullin** [comment]
Found what it does on the client side. So, it gzips and converts to base64 string. Would be great to have this in the documentation, so people would save time. 

<img width="1041" alt="image" src="https://user-images.githubusercontent.com/17814411/214666807-05147932-a273-481c-96ff-36ed837d2c32.png">

**Comment by arsamigullin** [comment]
Here is how we can do it in C#
```
string MissingMetrics = "let T = datatable(column1:int, column2:string)\r\n[\r\n  1, \"A\",\r\n  2, \"B\",\r\n  3, \"C\"\r\n];\r\nT\r\n|where column1 == 1";
string a = $"https://dataexplorer.azure.com/clusters/<cluster>/databases/<database>?query={CompressString(MissingMetrics)}";
Console.WriteLine(a);

static string CompressString(string text)
{
    byte[] buffer = Encoding.UTF8.GetBytes(text);
    using (var memoryStream = new MemoryStream())
    {
        using (var gZipStream = new GZipStream(memoryStream, CompressionMode.Compress, true))
        {
            gZipStream.Write(buffer, 0, buffer.Length);
        }
        memoryStream.Position = 0;

        var compressedData = new byte[memoryStream.Length];
        memoryStream.Read(compressedData, 0, compressedData.Length);
        return Convert.ToBase64String(memoryStream.ToArray());
    }
}
```

and for JavaScript
```
let query = 'let T = datatable(column1:int, column2:string)\r\n[\r\n  1, "A",\r\n  2, "B",\r\n  3, "C"\r\n];\r\nT\r\n|where column1 == 1';
let compressedString = a.gzip(e, {to:"string"});
let base64String = btoa(compressedString);
```

**Comment by RamanathanChinnappan-MSFT** [comment]
@arsamigullin 

For an issue like this, I'd recommend you create a [support ticket](https://azure.microsoft.com/support/create-ticket/) since the support team will be able to respond much more quickly and have a conversation with you to figure out what could be going on.


Since this issue isn't directly related to improving our docs, and to gain a better understanding of your issue, I'd recommend working closer with our support team via an [Azure support request] (https://docs.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request). Or you can leverage our Q&A forum by posting your issue there so our community, and MVPs can further assist you in troubleshooting this issue or finding potential workarounds.




[Teams Q&A forum] (https://docs.microsoft.com/en-us/answers/topics/46488/office-teams-windows-itpro.html) for technical questions about the configuration and administration of Microsoft Teams on Windows.
[Microsoft Teams Community forum] (https://answers.microsoft.com/en-us/msteams/forum?sort=LastReplyDate&dir=Desc&tab=All&status=all&mod=&modAge=&advFil=&postedAfter=&postedBefore=&threadType=All&isFilterExpanded=false&page=1
