### ISSUE TITLE
Unable to download kusto

### ISSUE THREAD

**Issue by gauravgahlot299** [MicrosoftDocs/dataexplorer-docs#177]
[Enter feedback here]
kusto download link doesnt work

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7ba96a1-65dd-5320-6d36-47de50b8403f
* Version Independent ID: deee5b70-9bd5-2bf9-f7b7-12c40200693d
* Content: [Getting started with Kusto.Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/tools/kusto-explorer)
* Content Source: [data-explorer/kusto/tools/kusto-explorer.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/tools/kusto-explorer.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by yonileibowitz** [comment]
Hi @gauravgahlot299 ,

could you please specify which link you've clicked on, what happened when you did, and what you mean by "doesn't work" in more detail?

**Comment by KranthiPakala-MSFT** [comment]
Hi @gauravgahlot299 , 

Could you please point us to the link you are referring to? - Thanks.

**Comment by gauravgahlot299** [comment]
on this page https://kusto.azurewebsites.net/docs/kusto/tools/kusto-explorer.html, when I click on install kusto explorer it redirects me to aka.ms/ke and that page never loads for me

**Comment by abbashus** [comment]
Similar issue #192.

**Comment by KranthiPakala-MSFT** [comment]
@gauravgahlot299 @abbashus What is the browser you are using? I was able to download it successfully without issue in Chrome. Have you tried using Chrome? If not could you please try and let us know? 

![image](https://user-images.githubusercontent.com/50185738/86185130-7702b080-baea-11ea-81df-e122f2a40f4f.png)

**Comment by abbashus** [comment]
I was able to install with Edge browser, still not working with Chrome.

**Comment by KranthiPakala-MSFT** [comment]
@abbashus Thanks for confirming. As this is an issue to specific users, I would recommend you to file a support request for deeper analysis. In case if you don't have a support plan, please feel free to email at AzCommunity@microsoft.com with below details so that we can work closely on this to investigate further. 

Subject of the email: [Attn - Kranthi : GitHub issue title]
Thread URL: [GitHub Issue URL]
Subscription ID:  [your subscription id]

We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply and reopen the issue. We will gladly continue the discussion.
