### ISSUE TITLE
Cx wants application to insert data in a SQLDB table that will then be used by application insights as a filter condition

### ISSUE THREAD

**Issue by mkennedy345** [MicrosoftDocs/dataexplorer-docs#303]
Cx wants application to insert data in a SQLDB table that will then be used by application insights as a filter condition. Need help

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f9edad54-ecb5-dc20-970d-214cce195a6f
* Version Independent ID: 9db1a075-410f-2933-6414-b92e5efd6385
* Content: [Cross-database & cross-cluster queries - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/cross-cluster-or-database-queries?pivots=azuredataexplorer)
* Content Source: [data-explorer/kusto/query/cross-cluster-or-database-queries.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/query/cross-cluster-or-database-queries.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by Grace-MacJones-MSFT** [comment]
Hi @mkennedy345, thanks for the Comment. We are actively investigating and will get back to you soon.

**Comment by KranthiPakala-MSFT** [comment]
Hi @mkennedy345  Thanks for leveraging Azure docs feedback channel to raise this question. This channel is reserved for ‘Azure docs’ feedback- for sharing doc feedback and suggesting content improvements. 

After reviewing the feedback, it seems that this issue is not related directly to the doc in reference. Hence, I would recommend you to please create a thread on the forums - [Microsoft Q&A](https://docs.microsoft.com/answers/index.html) or [Stack Overflow](https://stackoverflow.com/) and add tags accordingly. Once you post your issue on forums, it will have visibility across the community which has a better suited audience for such types of issues. 

We have our engineers and other community members who will be happy to assist. Please do share the forum thread link once it is posted. 

Thank you

**Comment by KranthiPakala-MSFT** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply and reopen the issue. We will gladly continue the discussion.

Please do share the forum link once it is created. 

Thank you
