### ISSUE TITLE
What are the steps to recover a deleted ADX dashboard?

### ISSUE THREAD

**Issue by baselsalam** [MicrosoftDocs/dataexplorer-docs#335]
One of our colleagues wants to recover an ADX dashboard they deleted.

We found some instructions, but those are for "Azure portal dashboards". 

How can we do this for ADX dashboards?

**Comment by KranthiPakala-MSFT** [comment]
Hi @baselsalam, 

Thanks for leveraging Microsoft docs feedback channel to raise this question. This channel is reserved for ‘Microsoft docs’ feedback- for sharing doc feedback and suggesting content improvements. Up on  reviewing this feedback, we are not able to determine any specific document related to this query.

Since your issue is specific to a use case, we request you to please reach out in forums like [Microsoft Q&A](https://docs.microsoft.com/answers/index.html) or [Stackoverflow](https://stackoverflow.com/questions). We have our engineers and other community members who will be happy to assist. Forums have a better suited audience for such queries. Once your issue is posted in forum, please do share the forum thread link here for tracking. 

If you have a document which you are following and if you think it needs an update, please let us know about that here.

We will now proceed to close this thread. If there are further questions regarding this matter, please reopen it and we will gladly continue the discussion.

Thank you
