### ISSUE TITLE
Network-secured Event Hub?

### ISSUE THREAD

**Issue by deyanp** [MicrosoftDocs/dataexplorer-docs#37]
What about event hub which is network-secured (Event Hubs -&gt; Networking -&gt; Firewalls and virtual networks -&gt; Selected Networks) with "Allow trusted Microsoft services to bypass the firewall" = Yes? 
Would the ingestion work?
If not, how can I allow access to ADX in Event Hubs -&gt; Networking -&gt; Firewalls and virtual networks -&gt; Selected Networks based on Public IP Address range (e.g. West Europe)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d5808ed2-5d09-4c56-dc0b-4e3650f8fc16
* Version Independent ID: ba034a8d-d5bb-6ea4-e61b-74ea3a5eb2be
* Content: [Ingest data from Event Hub into Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/ingest-data-event-hub)
* Content Source: [data-explorer/ingest-data-event-hub.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/ingest-data-event-hub.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by orspod** [comment]
@deyanp - thanks for your feedback/question.
@basaba - can you please assist?

**Comment by cosh** [comment]
Allow trusted Microsoft services to bypass this firewall? -> "This setting is related to firewall only. In order to access this event hub, the trusted service must also be given explicit permissions in the Access policies section."

if you would love to secure the eventhub to adx connection then you should deploy adx into a vnet https://docs.microsoft.com/en-us/azure/data-explorer/vnet-deployment and configure the eventhub with service endpoints in the respective subnet.

**Comment by deyanp** [comment]
Thanks, @cosh , thus is what I have to do (spawn a new cluster and migrate all data to it somehow)

**Comment by orspod** [comment]
@cosh thanks for your assistance. @deyanp since your question has been addressed, I will now close the issue. Feel free to reach out with any additional questions.
