### ISSUE TITLE
Table with Streaming Ingestion enabled

### ISSUE THREAD

**Issue by vivere-dally** [MicrosoftDocs/dataexplorer-docs#491]
Hello,

Is it possible to make some sort of duplicate detection like the one in this [example](https://docs.microsoft.com/en-us/azure/data-explorer/dealing-with-duplicates#solution-3-filter-duplicates-during-the-ingestion-process)?

In my case DeviceEventsAll Table has streaming ingestion enabled and when I try to replicate the update policy for DeviceEventsUnique I get the following error:
Error during execution of a policy operation: Referencing additional tables from update policy is not allowed when the source table has a StreamingIngestion policy defined. Additional tables: DeviceEventsUnique.

Is it possible to do duplicate detection for this case? If it is, how do we get past that error? If not please specify in the docs.

Thanks.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 69d81d6e-8715-ccdc-ba99-ddbb61c7b86e
* Version Independent ID: a051de71-7527-5f6c-718f-ceee739a7756
* Content: [Handle duplicate data in Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/dealing-with-duplicates)
* Content Source: [data-explorer/dealing-with-duplicates.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/dealing-with-duplicates.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by NavtejSaini-MSFT** [comment]
@vivere-dally We are checking this and will get back to you.

**Comment by NavtejSaini-MSFT** [comment]
@vivere-dally We have checked with our PG team and got below info:
"This article is not current (we will fix it). We now have materialized views that can be used for the deduplication and provide much simpler interface. There is one catch though and it is that for streaming scenarios the support is still in beta since the "cursor" feature is streaming is still in preview and need to be enabled on the specific cluster. Here is the link for materialized views, search in the page for dedup [Materialized views - Azure Data Explorer | Microsoft Docs](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/management/materialized-views/materialized-view-overview)

We can start a conversation regarding your cluster with them. Let us know if you want to go that route and we will provide further detail.
@orspod - Avner Aharoni conveyed to update this document. Please convey you will the POC for the same.

**Comment by orspod** [comment]
@NavtejSaini-MSFT - thanks for your help.
I created a [WI](https://mseng.visualstudio.com/TechnicalContent/_queries/edit/1800148/?fullScreen=true&triage=true) to update this doc. FYI @avneraa

**Comment by NavtejSaini-MSFT** [comment]
@vivere-dally At this point we are going ahead and closing this feedback. Please get back to us if any questions.

Thank you @orspod for creating workitem to update the document.
