### ISSUE TITLE
Add ifexists flag

### ISSUE THREAD

**Issue by vivere-dally** [MicrosoftDocs/dataexplorer-docs#531]
Hello,

I have some automation scripts which drops and creates some tables/functions/materialized-views. The tables and functions allow for the following syntax: .drop table <tableName> ifexists, which is very convenient, but the MV doesn't.

Consider adding this feature.

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aff2ca96-3fa2-e1d8-0ab6-acf773180e3b
* Version Independent ID: 946c1113-b966-fd17-f8c2-513071e1ede2
* Content: [Materialized views drop - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/management/materialized-views/materialized-view-drop)
* Content Source: [data-explorer/kusto/management/materialized-views/materialized-view-drop.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/management/materialized-views/materialized-view-drop.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **yifats**

**Comment by KranthiPakala-MSFT** [comment]
@vivere-dally Thanks for the feedback and brining this to our attention. Since the feedback is related to product feature request, I would request you to please log a feature request suggestion in Azure Data Explorer user voice forum: 
https://feedback.azure.com/forums/915733-azure-data-explorer

All the feedback  shared in this forum are actively monitored and reviewed by ADX engineering team.  Also please do share the feedback link  here, once it is posted  so that other users with similar idea can up-vote  and/or comment on your suggestion which would help to increase the priority of feature implementations. 

Hope this info helps. 

Closing this issue based on this update. 
Thank you for the feedback!
