### ISSUE TITLE
To fix the link in the article which is no longer available

### ISSUE THREAD

**Issue by docast** [MicrosoftDocs/dataexplorer-docs#532]
[Enter feedback here]
The article, has a section called "This article is also available as an Azure Notebook." and has a hyperlink to launch Azure notebook. But the link is no longer valid given that Azure notebooks preview is retired and getting "page not found" error. 

Feedback: 
To fix the broken link or to remove the retired link from the doc.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 68d5f8ab-85c7-19bf-d91a-e76e81c76d7b
* Version Independent ID: 161a10d8-fc7f-97e8-b13e-0ddc7dd4f3c6
* Content: [Ingest JSON formatted data into Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/ingest-json-formats?tabs=python)
* Content Source: [data-explorer/ingest-json-formats.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/ingest-json-formats.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by KranthiPakala-MSFT** [comment]
@docast  
Thanks for the feedback and bringing this to our notice. At this time we are reviewing the feedback and will update the document as appropriate.

**Comment by KranthiPakala-MSFT** [comment]
Hi @docast I don't see the section called "This article is also available as an Azure Notebook." in this doc: https://docs.microsoft.com/azure/data-explorer/ingest-json-formats?tabs=python 

Could you please point me to exact location of the doc which your are referring to? In case if your feedback relates to a different document, I would recommend you to please open an issue on that particular doc. 

If it related to this doc, please help me in pointing to the appropriate location so that we can review and make the changes accordingly. 

Looking forward to your confirmation. 

Thank you.

**Comment by docast** [comment]
HI, the below link need to be looked at:
https://docs.microsoft.com/en-us/azure/data-explorer/python-ingest-data

In the above link, it has a line called "This article is also available as an Azure Notebook<https://notebooks.azure.com/ManojRaheja/libraries/KustoPythonSamples/html/QueuedIngestSingleBlob.ipynb>." Which points to a broken link.

Regards,
Don Rohan Castelino

**Comment by KranthiPakala-MSFT** [comment]
@docast Appreciate much for the feedback and pointed to the exact location of the issue. 
The PR for the fix has been created and it will be merged soon. Thanks again for pointing this out, I am closing the issue based on this update, please let us know if there is something else that we can help you with.
