### ISSUE TITLE
multijson/JSON ingestion mismatch: provide information about BadRequest_InvalidBlob: BadRequest_EmptyBlob error 

### ISSUE THREAD

**Issue by derSchtefan** [MicrosoftDocs/dataexplorer-docs#627]
We were spending a considerable amount of time trying to fix the issue that a manual ingest of a GZIP compressed JSON file containing multiple records succeeded if run via the portal, but failed with "BadRequest_InvalidBlob: BadRequest_EmptyBlob" when run via Event Grid / Event Hub, or .ingest into table commands.

It turns out the problem was us not realizing that the ingest format is multijson, not json. The reason this is misleading is:

- BadRequest_InvalidBlob: BadRequest_EmptyBlob is not very well documented. The Blob is neither invalid nor empty, and worked fine in the portal. We spent too much time debugging access permissions, etc.
- Everywhere else in the documentation there is always only "json" mentioned. 
- multijson and json have counterintuitive meanings for a newcomer. 
- The name "multiline json" in the dropdown when creating a new Event Grid ingestion is counterintuitive as well: In both cases I would expect "multiline json" to be exactly the oposite: json objects seperated by a newline, instead of a valid "json" array. 
- [The documentation we then found](https://docs.microsoft.com/en-us/azure/data-explorer/ingest-json-formats?tabs=kusto-query-language) is also describing the json/multiline json counterintuitively. Our json file actually is an ordinary array, and has no line seperators at all.

To improve the situation the following could be attempted:

- When looking up the error "BadRequest_InvalidBlob: BadRequest_EmptyBlob", a "typical problems" section in the documentation could help
- The error messages in question could refer to a multijson/json mismatch
- The existence of "multijson" could be mentioned at other places in the documentation, for instance the ingestion mapping, the ingest commands, or the ingest properties
- The error message itself could be changed, maybe hinting at a multijson/json mismatch

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 68d5f8ab-85c7-19bf-d91a-e76e81c76d7b
* Version Independent ID: 161a10d8-fc7f-97e8-b13e-0ddc7dd4f3c6
* Content: [Ingest JSON formatted data into Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/ingest-json-formats?tabs=kusto-query-language)
* Content Source: [data-explorer/ingest-json-formats.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/ingest-json-formats.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by JamesTran-MSFT** [comment]
@derSchtefan 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by YaelSchuster** [comment]
@vladikbr

**Comment by YaelSchuster** [comment]
Hi @derSchtefan thanks for reaching out. I understand you have been in touch with the Kusto team by email to work on this issue and that they have identified three problems:
* Kusto.Explorer unable to infer (and ingest) multiline JSON data unless the correct format was specified
* Kusto.Explorer unable to create an identity JSON mapping for arrays of JSON records (fixed in the last version of KE)
* “EmptyBlob” documentation does not refer to a possible mistake in data format specification – we need to link the errors doc on “BadRequest_InvalidBlob: BadRequest_EmptyBlob” error to point out the possibility of wrong format specification and explicitly refer to the supported formats docs.

I have opened a WI to address the EmptyBlob documentation problem and I understand the other issues were resolved by @vladikbr. At this time I will close the issue. Please feel free to reach out with further questions or comments.

https://mseng.visualstudio.com/TechnicalContent/_workitems/edit/1821526

#please-close
