### ISSUE TITLE
Datatype returned by dayofweek() is Timespan and not Int as document states

### ISSUE THREAD

**Issue by gitmadness** [MicrosoftDocs/dataexplorer-docs#637]
The data type returned by the function dayofweek() is Timespan but the documentation says it is an Int. 

e.g. 

`print dayofweek(datetime(2021-03-04))`

returned

> print_0
> --
> 4.00:00:00

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b9f82871-793a-1887-529a-0e7d9fd7df77
* Version Independent ID: 5d6ae62b-1975-2c82-71b9-cffbb94333e8
* Content: [dayofweek() - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/dayofweekfunction)
* Content Source: [data-explorer/kusto/query/dayofweekfunction.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/query/dayofweekfunction.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by himanshusinha-msft** [comment]
Thanks for the feedback and bringing this to our notice . At this time we are reviewing the feedback and will update the document as appropriate .

**Comment by himanshusinha-msft** [comment]
Hello @gitmadness , 
Thanks for the feedback and I did checked the point which you did brought up . 

print dayofweek(datetime(2021-03-09))
-- 2.00:00:00

As per the document its says "Returns the integer number of days since the preceding Sunday, as a **timespan**." To my  understanding this is what we are seeing  & the document at this time does not require any update . We will go ahead and close the issue now , you can always reopen the issue if you think thats appropiate .
