### ISSUE TITLE
Unclear explanation of shuffle query correctness

### ISSUE THREAD

**Issue by Cutuy** [MicrosoftDocs/dataexplorer-docs#659]
The reason of shuffle query may be producing incorrect result is not clearly explained. Examples that may lead to such incorrect shuffle query is verbose. 

Kusto's behavior on incorrect usage of shuffle query is not documented. Kusto seems to ignore inappropriate `shufflekey`s when `hint.strategy=shuffle` is specified, and fail if these keys were explicitly specified with `hint.shufflekey=<joinkey_n>`.

As mentioned in doc, shuffle query may return incorrect results due to below reason. It still does not explain why. If similar values are _not_ in the same partition, how would the query go wrong?

> The summarize operator on the left side of the join expects similar values of the column ActivityId to be in the same partition.

It is my understanding that,

* A `shuffle` join hashes the data from the left table, then sends it to nodes that have data from the right data with a matching hash, where data is joined. Each node processes the data independently.

* The given example will result in 1 row of data from the right table (each has hash 56 & 65) to be joined with the summarized (using `any`) result of 1 row of data from the left table, on each of the 2 nodes. 

* This means the summarization is performed on partial not full results having the same `ActivityId`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 563768b5-021b-9d7a-98cd-a630f67b02fd
* Version Independent ID: 2c0fe763-005d-5532-a7b4-9697e29dd380
* Content: [Shuffle query - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/shufflequery)
* Content Source: [data-explorer/kusto/query/shufflequery.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/query/shufflequery.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by CHEEKATLAPRADEEP-MSFT** [comment]
@Cutuy  Thanks for the feedback! I have assigned the issue to the content author to evaluate and update as appropriate.

**Comment by ziham1531991** [comment]
Hi Cutuy,

We've updated our docs and made it more clear.
Kusto will not return wrong results in that case, it will ignore the parameter hint.strategy=shuffle / hint.shufflekey = <key> when it is not valid.
I believe the docs is confusing and was not clear that the hint will be ignored so Thanks again for reporting this.

Now regarding why the hint is ignored in that case, it is because for each operator that runs in shuffle strategy, e.g: join by key = K1, we expect that both sides of the joins are shuffled by the same hash function H, key and N (partitions number) H(key,N) since the assumption in shuffle query that each join which runs in the context of partition X in some cluster node will get the same values of K1 from both join sides. otherwise, we may get wrong results if we use different hash function, different key or different N.

**Comment by YaelSchuster** [comment]
@Cutuy since it looks like you got an answer above, I'm going to go ahead and close this issue. If you have any followup questions, please feel free to @mention myself or Ziad (@ziham1531991). Thanks!

#please-close

**Comment by Cutuy** [comment]
Thanks for the quick updates. Appreciated!
