### ISSUE TITLE
The result of section "Equality and inequality of null values" is incorrect.

### ISSUE THREAD

**Issue by jianfeng-jia** [MicrosoftDocs/dataexplorer-docs#670]
[Enter feedback here]
The result of equality-and-inequality-of-null-values is incorrect in page
https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/scalar-data-types/null-values?pivots=azuredataexplorer#equality-and-inequality-of-null-values

It should be 
5	true	true	false	true
null	false	true	false	true
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54b8c137-22c6-18b2-d07e-cc9e76e4dabb
* Version Independent ID: 82558980-9bca-1dcf-dba7-b59c94fc22ab
* Content: [Null Values - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/scalar-data-types/null-values?pivots=azuredataexplorer)
* Content Source: [data-explorer/kusto/query/scalar-data-types/null-values.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/query/scalar-data-types/null-values.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by BryanTrach-MSFT** [comment]
@jianfeng-jia Thanks for the feedback! We are currently investigating and will update you shortly.

**Comment by himanshusinha-msft** [comment]
We have assigned the issue to the content author . They will evaluate & update the document as appropriate

**Comment by YaelSchuster** [comment]
Hi @jianfeng-jia thanks for reaching out with your question.
If you notice in the explanation section, 
![image](https://user-images.githubusercontent.com/62833511/116358803-b67f5380-a806-11eb-9fa5-c8129c2866a3.png)
as noted in the docs (image above), applying the equality operator to two null values yields null. The same is true for the inequality operator. 

If you try the example in Azure Data Explorer, you will get the following results ( I have added in a few extra values just for fun):
![image](https://user-images.githubusercontent.com/62833511/116358984-ecbcd300-a806-11eb-9ac1-ca3e548f5c21.png)


At this time, I am closing the issue since the docs are correct. If you have any further questions, please feel free to reach out.

#please-close
