### ISSUE TITLE
wrong endpoints

### ISSUE THREAD

**Issue by alexchen2016** [MicrosoftDocs/dataexplorer-docs#923]
In segment "Additional syntax examples", for endpoints in the China 21Vianet, should be "cluster(`https://adx.monitor.azure.cn..."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f6c8fe3-d9a3-f11b-cfe7-f0f67f44b0d5
* Version Independent ID: 418e6ed4-24b4-689b-50fc-490441dc393c
* Content: [Query data in Azure Monitor with Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/query-monitor-data)
* Content Source: [data-explorer/query-monitor-data.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/query-monitor-data.md)
* Service: **data-explorer**
* GitHub Login: @osalzberg
* Microsoft Alias: **orens**

**Comment by osalzberg** [comment]
Thanks! My typo

Fixed it

Best regards,
Oren Salzberg

From: Alex Chen ***@***.***>
Date: Monday, 29 November 2021 at 9:27
To: MicrosoftDocs/dataexplorer-docs ***@***.***>
Cc: Oren Salzberg ***@***.***>, Mention ***@***.***>
Subject: [MicrosoftDocs/dataexplorer-docs] wrong endpoints (Issue #923)

In segment "Additional syntax examples", for endpoints in the China 21Vianet, should be "cluster(`https://adx.monitor.azure.cn<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fadx.monitor.azure.cn%2F&data=04%7C01%7COren.Salzberg%40microsoft.com%7C66bc95f7606c4a03268208d9b309a02f%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637737676214594754%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=5xjMHerZP2i9JMHUEMKpvkYcGkhfNkSf%2BY9fKW0%2BDuM%3D&reserved=0>..."

________________________________
Document Details

⚠ Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.

  *   ID: 6f6c8fe3-d9a3-f11b-cfe7-f0f67f44b0d5
  *   Version Independent ID: 418e6ed4-24b4-689b-50fc-490441dc393c
  *   Content: Query data in Azure Monitor with Azure Data Explorer<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fazure%2Fdata-explorer%2Fquery-monitor-data&data=04%7C01%7COren.Salzberg%40microsoft.com%7C66bc95f7606c4a03268208d9b309a02f%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637737676214594754%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Xixj8WewkEx65YF%2FIVgUNrem%2FdRUn%2BZBnG0DA09qENE%3D&reserved=0>
  *   Content Source: data-explorer/query-monitor-data.md<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2Fdataexplorer-docs%2Fblob%2Fmaster%2Fdata-explorer%2Fquery-monitor-data.md&data=04%7C01%7COren.Salzberg%40microsoft.com%7C66bc95f7606c4a03268208d9b309a02f%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637737676214594754%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=GpRjtnAk2LGLXRTqDFojyW0gBaSmp986pl1R3tohU%2Bo%3D&reserved=0>
  *   Service: data-explorer
  *   GitHub Login: @osalzberg<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fosalzberg&data=04%7C01%7COren.Salzberg%40microsoft.com%7C66bc95f7606c4a03268208d9b309a02f%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637737676214594754%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=gQhlACgfqtXDM6onV5uVvtR9j0FwWOMkAxY9UsXpSP0%3D&reserved=0>
  *   Microsoft Alias: orens

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2Fdataexplorer-docs%2Fissues%2F923&data=04%7C01%7COren.Salzberg%40microsoft.com%7C66bc95f7606c4a03268208d9b309a02f%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637737676214594754%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=ee3Eui4l9BE%2F5wGOEmOmLDkr9B%2BRJqn0EKeYQms2KPg%3D&reserved=0>, or unsubscribe<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAQHAB26DLTDG2DLLUOT2MGDUOMTMBANCNFSM5I6NERPQ&data=04%7C01%7COren.Salzberg%40microsoft.com%7C66bc95f7606c4a03268208d9b309a02f%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637737676214594754%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=bSCCa6pl9BH%2FBggkPpixBGmVEvA7V0ruf0ZjGpxvRN4%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7COren.Salzberg%40microsoft.com%7C66bc95f7606c4a03268208d9b309a02f%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637737676214594754%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=OcR6zfeMk0iO23pY%2BBTDbFiDe%2B620Gzmt4NSWqq9JtU%3D&reserved=0> or Android<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7COren.Salzberg%40microsoft.com%7C66bc95f7606c4a03268208d9b309a02f%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637737676214594754%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=EMMrZGJegE%2B4Qx9H03Lf1ETvyvxHjGgmA9sPjzIIZrc%3D&reserved=0>.

**Comment by ShaikMaheer-MSFT** [comment]
@alexchen2016 Thank you for sharing feedback. We are actively monitoring it. We will share updates soon.

**Comment by osalzberg** [comment]
Hi, I have updated the docs. I had a typo.

thanks Alex

**Comment by ShaikMaheer-MSFT** [comment]
Thank you @osalzberg. Closing issue as doc update taken care.
