### ISSUE TITLE
Question - Can I define the delimiter

### ISSUE THREAD

**Issue by Assafkalfa** [MicrosoftDocs/dataexplorer-docs#935]
delete pls, tnx

#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 278a7ae3-4eba-a252-b4e8-66e04ea280a5
* Version Independent ID: 6812cf36-c5de-eefb-2217-a89d0efe221f
* Content: [extract() - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/extractfunction)
* Content Source: [data-explorer/kusto/query/extractfunction.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/query/extractfunction.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by AjayKumar-MSFT** [comment]
Assafkalfa,  Thanks for leveraging Azure docs feedback channel to raise this question and much appreciate the follow-up. Since you have closed the thread I presume the issue is resolved, if it's not the case or you need further assistance kindly just let us know.

- As a side note, this channel is reserved for ‘Azure docs’ feedback- for sharing doc feedback and suggesting content improvements.
